// <auto-generated />
namespace MISTeam8.Migrations.Team8Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Team8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Team8));
        
        string IMigrationMetadata.Id
        {
            get { return "202203041804506_Team8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
